import Head from "next/head";
import GlobalLayout from "@/components/layout";
import "@/styles/globals.css";
import GlobalNotification from "@/helper/globalNotification";

export default function App({ Component, pageProps }) {
  return <>
    <Head>
      <title>SYS Challenge</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <GlobalNotification>
      <GlobalLayout pageTitle={Component.pageTitle}>
        <Component {...pageProps} />
      </GlobalLayout>
    </GlobalNotification>
  </>;
}